# Generated by Django 5.2.5 on 2025-09-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='folio',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
