# Generated by Django 5.2.5 on 2025-09-11 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_serviceorder_folio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='checkin_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'Recibido'), ('REV', 'En revisión'), ('WAI', 'En espera de repuestos'), ('AUTH', 'Requiere autorización de repuestos'), ('READY', 'Listo para recoger'), ('DONE', 'Entregado')], db_index=True, default='NEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='status',
            field=models.CharField(choices=[('NEW', 'Recibido'), ('REV', 'En revisión'), ('WAI', 'En espera de repuestos'), ('AUTH', 'Requiere autorización de repuestos'), ('READY', 'Listo para recoger'), ('DONE', 'Entregado')], db_index=True, max_length=10),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('delta', 0), _negated=True), name='inv_delta_nonzero'),
        ),
    ]
