# Generated by Django 5.2.5 on 2025-09-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inventory_min_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'Recibido'), ('REV', 'En revision'), ('WAI', 'En espera de repuestos'), ('AUTH', 'Requiere autorizacion de repuestos'), ('READY', 'Listo para recoger'), ('DONE', 'Entregado')], db_index=True, default='NEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='status',
            field=models.CharField(choices=[('NEW', 'Recibido'), ('REV', 'En revision'), ('WAI', 'En espera de repuestos'), ('AUTH', 'Requiere autorizacion de repuestos'), ('READY', 'Listo para recoger'), ('DONE', 'Entregado')], db_index=True, max_length=10),
        ),
    ]
