# Generated by Django 5.2.7 on 2025-10-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='apply_tax',
            field=models.BooleanField(default=True),
        ),
    ]
