# Generated by Django 5.2.7 on 2025-10-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_estimate_apply_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
