# Generated by Django 5.2.7 on 2025-11-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification_seen_at_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='statushistory',
            name='author_role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('NEW', 'Recibido'), ('REV', 'En revision'), ('WAI', 'En espera de repuestos'), ('AUTH', 'Requiere autorizacion de repuestos'), ('READY', 'Listo para recoger'), ('DONE', 'Entregado')], default='', max_length=10),
        ),
    ]
