# Generated by Django 5.2.7 on 2025-11-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_statushistory_author_role_statushistory_from_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='inventory_applied',
            field=models.BooleanField(default=False),
        ),
    ]
