# Generated by Django 5.2.7 on 2025-11-18 16:48

import django.db.models.deletion
from django.db import migrations, models


def populate_order_relations(apps, schema_editor):
    ServiceOrder = apps.get_model('core', 'ServiceOrder')
    Payment = apps.get_model('core', 'Payment')
    Device = apps.get_model('core', 'Device')

    for order in ServiceOrder.objects.select_related('device__customer'):
        customer = None
        if order.customer_id:
            customer = order.customer
        elif order.device_id:
            device = getattr(order, 'device', None)
            if device:
                customer = getattr(device, 'customer', None)
                if customer:
                    order.customer = customer
                    order.save(update_fields=['customer'])
        if order.device_id:
            try:
                order.devices.add(order.device)
            except Device.DoesNotExist:
                continue

    for payment in Payment.objects.select_related('order__device'):
        if payment.device_id:
            continue
        order = getattr(payment, 'order', None)
        if order and order.device_id:
            payment.device_id = order.device_id
            payment.save(update_fields=['device'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_estimate_inventory_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.device'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.customer'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='orders', to='core.device'),
        ),
        migrations.RunPython(populate_order_relations, migrations.RunPython.noop),
    ]
