# Generated by Django 5.2.7 on 2025-11-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_payment_device_serviceorder_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='accessories_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='device',
            name='password_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='device',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
