name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: config.settings

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Create .env for CI
        run: |
          cat > .env << 'EOF'
          SECRET_KEY=ci-secret-key
          DEBUG=True
          ALLOWED_HOSTS=127.0.0.1,localhost
          EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
          EMAIL_PORT=0
          EOF

      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt

      - name: Migrate (SQLite)
        run: python manage.py migrate --noinput

      - name: Django checks
        run: python manage.py check

      - name: Run tests
        run: python manage.py test -v 2
