name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: config.settings

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      # 🔧 Dependencias del sistema para pycairo/cairo (PDF/imagenes)
      - name: Install system libraries (cairo/pango/jpeg/etc)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcairo2-dev \
            libpango1.0-dev \
            libgdk-pixbuf2.0-dev \
            libffi-dev \
            libjpeg-dev \
            zlib1g-dev \
            pkg-config

      - name: Create .env for CI
        run: |
          cat > .env << 'EOF'
          SECRET_KEY=ci-secret-key
          DEBUG=True
          ALLOWED_HOSTS=127.0.0.1,localhost
          EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
          EMAIL_PORT=0
          EOF

      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt

      # Primero migramos (evita que `check` truene por tablas faltantes)
      - name: Migrate (SQLite)
        run: python manage.py migrate --noinput

      - name: Django checks
        run: python manage.py check

      - name: Run tests
        run: python manage.py test -v 2
